version: v0.8.0-alpha.3

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://*.localhost:3000
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
        - X-CSRF-Token
        - Access-Control-Allow-Credentials
        - Access-Control-Allow-Origin
      exposed_headers:
        - Content-Type
        - Set-Cookie
        - Access-Control-Allow-Credentials
        - Access-Control-Allow-Origin
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/
  whitelisted_return_urls:
    - http://localhost:3000

  methods:
    link:
      enabled: true
    password:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:3000/error

    settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery

    verification:
      enabled: true
      ui_url: http://localhost:3000/verification
      after:
        default_browser_return_url: http://localhost:3000/

    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login

    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/auth/registration
      after:
        password:
          hooks:
            - 
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true



secrets:
  cookie:
    - 4159f931cce7cc16d5c17814d76686d960d6ee40675faca165067eb1faa9bd4fa9beb9e1a2a689b2003355ae5746a283bf591f34dbc0e4d8f4a0685e753000b3
  cipher:
    - Vf2nS{+jwj"{U:BHLZ4V/Mz.As)]uKQ'

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true